// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# Weaviate is an open source, AI-native vector database. This client connects to the Weaviate REST API v1 to manage collections, objects, searches, tenants, backups, replication, users and roles.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://localhost:8080/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List available endpoints
    #
    # + headers - Headers to be sent with the request 
    # + return - Weaviate is alive and ready 
    remote isolated function listEndpoints(map<string|string[]> headers = {}) returns EndpointListResponse|error {
        string resourcePath = string `/`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Check application liveness
    #
    # + headers - Headers to be sent with the request 
    # + return - The application is alive and responding to HTTP requests 
    remote isolated function checkLiveness(map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/.well-known/live`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Check application readiness
    #
    # + headers - Headers to be sent with the request 
    # + return - The application is ready to serve traffic 
    remote isolated function checkReadiness(map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/.well-known/ready`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get OIDC configuration
    #
    # + headers - Headers to be sent with the request 
    # + return - OIDC configuration details returned successfully 
    remote isolated function getOidcConfiguration(map<string|string[]> headers = {}) returns OidcConfiguration|error {
        string resourcePath = string `/.well-known/openid-configuration`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Initiate a replica movement
    #
    # + headers - Headers to be sent with the request 
    # + payload - Replica movement details: collection, shard, source and target nodes 
    # + return - Replication operation registered successfully. ID of the operation is returned 
    remote isolated function startReplication(ReplicationReplicateReplicaRequest payload, map<string|string[]> headers = {}) returns ReplicationReplicateReplicaResponse|error {
        string resourcePath = string `/replication/replicate`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete all replication operations
    #
    # + headers - Headers to be sent with the request 
    # + return - Replication operation registered successfully 
    remote isolated function deleteAllReplications(map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/replication/replicate`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Force delete replication operations
    #
    # + headers - Headers to be sent with the request 
    # + payload - Filter selecting the replication operations to force delete 
    # + return - Replication operations force deleted successfully 
    remote isolated function forceDeleteReplications(ReplicationReplicateForceDeleteRequest payload, map<string|string[]> headers = {}) returns ReplicationReplicateForceDeleteResponse|error {
        string resourcePath = string `/replication/replicate/force-delete`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Retrieve a replication operation
    #
    # + id - The ID of the replication operation to get details for
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The details of the replication operation 
    remote isolated function getReplication(string id, map<string|string[]> headers = {}, *GetReplicationQueries queries) returns ReplicationReplicateDetailsReplicaResponse|error {
        string resourcePath = string `/replication/replicate/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete a replication operation
    #
    # + id - The ID of the replication operation to delete
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted 
    remote isolated function deleteReplication(string id, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/replication/replicate/${getEncodedUri(id)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List replication operations
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The details of the replication operations 
    remote isolated function listReplications(map<string|string[]> headers = {}, *ListReplicationsQueries queries) returns ReplicationReplicateDetailsReplicaResponse[]|error {
        string resourcePath = string `/replication/replicate/list`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Cancel a replication operation
    #
    # + id - The ID of the replication operation to cancel
    # + headers - Headers to be sent with the request 
    # + return - Successfully cancelled 
    remote isolated function cancelReplication(string id, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/replication/replicate/${getEncodedUri(id)}/cancel`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get sharding state
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved sharding state 
    remote isolated function getCollectionShardingState(map<string|string[]> headers = {}, *GetCollectionShardingStateQueries queries) returns ReplicationShardingStateResponse|error {
        string resourcePath = string `/replication/sharding-state`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get replication scale plan
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Replication scale plan showing node additions and removals per shard 
    remote isolated function getReplicationScalePlan(map<string|string[]> headers = {}, *GetReplicationScalePlanQueries queries) returns ReplicationScalePlan|error {
        string resourcePath = string `/replication/scale`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Apply replication scaling plan
    #
    # + headers - Headers to be sent with the request 
    # + payload - The replication scaling plan specifying the collection and its shard-level replica adjustments 
    # + return - List of replication shard copy operation IDs initiated for the scale operation 
    remote isolated function applyReplicationScalePlan(ReplicationScalePlan payload, map<string|string[]> headers = {}) returns ReplicationScaleApplyResponse|error {
        string resourcePath = string `/replication/scale`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get current user info
    #
    # + headers - Headers to be sent with the request 
    # + return - Info about the user 
    remote isolated function getOwnUserInfo(map<string|string[]> headers = {}) returns UserOwnInfo|error {
        string resourcePath = string `/users/own-info`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List all users
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Info about the users 
    remote isolated function listUsers(map<string|string[]> headers = {}, *ListUsersQueries queries) returns DBUserInfo[]|error {
        string resourcePath = string `/users/db`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Export all database-user credentials
    #
    # + headers - Headers to be sent with the request 
    # + return - The exported user credentials 
    remote isolated function exportDbUsers(map<string|string[]> headers = {}) returns UserExportResponse|error {
        string resourcePath = string `/experimental/export-db-users`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Import database-user credentials
    #
    # + headers - Headers to be sent with the request 
    # + payload - Database user credentials to import, with their hashes and status 
    # + return - The per-user import results 
    remote isolated function importDbUsers(UserImportRequest payload, map<string|string[]> headers = {}) returns UserImportResponse|error {
        string resourcePath = string `/experimental/import-db-users`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get user info
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Info about the user 
    remote isolated function getUser(string userId, map<string|string[]> headers = {}, *GetUserQueries queries) returns DBUserInfo|error {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a new user
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + payload - Optional settings for creating the database user 
    # + return - User created successfully and API key returned 
    remote isolated function createUser(string userId, CreateUserRequest payload, map<string|string[]> headers = {}) returns UserApiKey|error {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a user
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted 
    remote isolated function deleteUser(string userId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Rotate API key of a user
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + return - API key successfully updated 
    remote isolated function rotateUserApiKey(string userId, map<string|string[]> headers = {}) returns UserApiKey|error {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}/rotate-key`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Activate a user
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + return - User successfully activated 
    remote isolated function activateUser(string userId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}/activate`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Deactivate a user
    #
    # + userId - The name of the user
    # + headers - Headers to be sent with the request 
    # + payload - Options for deactivating the user, including key revocation 
    # + return - User successfully deactivated 
    remote isolated function deactivateUser(string userId, DeactivateUserRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/users/db/${getEncodedUri(userId)}/deactivate`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get all roles
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful response 
    remote isolated function listRoles(map<string|string[]> headers = {}) returns RolesListResponse|error {
        string resourcePath = string `/authz/roles`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new role
    #
    # + headers - Headers to be sent with the request 
    # + payload - Role name and the permissions granted to the new role 
    # + return - Role created successfully 
    remote isolated function createRole(Role payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/roles`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Add permissions to a role
    #
    # + id - The name (ID) of the role being modified
    # + headers - Headers to be sent with the request 
    # + payload - Permissions to add to the role 
    # + return - Permissions added successfully 
    remote isolated function addRolePermissions(string id, AddRolePermissionsRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/add-permissions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove permissions from a role
    #
    # + id - The name of the role being modified
    # + headers - Headers to be sent with the request 
    # + payload - Permissions to remove from the role 
    # + return - Permissions removed successfully 
    remote isolated function removeRolePermissions(string id, RemoveRolePermissionsRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/remove-permissions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a role
    #
    # + id - The name of the role
    # + headers - Headers to be sent with the request 
    # + return - Successful response 
    remote isolated function getRole(string id, map<string|string[]> headers = {}) returns Role|error {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete a role
    #
    # + id - The name of the role
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted 
    remote isolated function deleteRole(string id, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Check whether a role possesses a permission
    #
    # + id - The name of the role
    # + headers - Headers to be sent with the request 
    # + payload - The permissions to be checked 
    # + return - Permission check was successful 
    remote isolated function checkRolePermission(string id, Permission payload, map<string|string[]> headers = {}) returns boolean|error {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/has-permission`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get users assigned to a role (deprecated)
    #
    # + id - The name of the role
    # + headers - Headers to be sent with the request 
    # + return - Users assigned to this role 
    # 
    # # Deprecated
    @deprecated
    remote isolated function getRoleUsers(string id, map<string|string[]> headers = {}) returns string[]|error {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/users`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get users assigned to a role
    #
    # + id - The name (ID) of the role
    # + headers - Headers to be sent with the request 
    # + return - Users assigned to this role 
    remote isolated function getRoleUserAssignments(string id, map<string|string[]> headers = {}) returns RoleUserAssignment[]|error {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/user-assignments`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get groups that have a specific role assigned
    #
    # + id - The unique name of the role
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the list of groups that have the role assigned 
    remote isolated function getRoleGroupAssignments(string id, map<string|string[]> headers = {}) returns RoleGroupAssignment[]|error {
        string resourcePath = string `/authz/roles/${getEncodedUri(id)}/group-assignments`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get roles assigned to a user (deprecated)
    #
    # + id - The name of the user
    # + headers - Headers to be sent with the request 
    # + return - Roles assigned to the user 
    # 
    # # Deprecated
    @deprecated
    remote isolated function getUserRoles(string id, map<string|string[]> headers = {}) returns RolesListResponse|error {
        string resourcePath = string `/authz/users/${getEncodedUri(id)}/roles`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get roles assigned to a user
    #
    # + id - The name of the user
    # + userType - The type of the user
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Roles assigned to the user 
    remote isolated function getUserRolesByType(string id, "oidc"|"db" userType, map<string|string[]> headers = {}, *GetUserRolesByTypeQueries queries) returns RolesListResponse|error {
        string resourcePath = string `/authz/users/${getEncodedUri(id)}/roles/${getEncodedUri(userType)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Assign a role to a user
    #
    # + id - The name of the user
    # + headers - Headers to be sent with the request 
    # + payload - Roles to assign to the user and the user type 
    # + return - Role assigned successfully 
    remote isolated function assignRoleToUser(string id, AssignRoleToUserRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/users/${getEncodedUri(id)}/assign`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Revoke a role from a user
    #
    # + id - The name of the user
    # + headers - Headers to be sent with the request 
    # + payload - Roles to revoke from the user and the user type 
    # + return - Roles revoked successfully 
    remote isolated function revokeRoleFromUser(string id, RevokeRoleFromUserRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/users/${getEncodedUri(id)}/revoke`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Assign a role to a group
    #
    # + id - The name of the group
    # + headers - Headers to be sent with the request 
    # + payload - Roles to assign to the group and the group type 
    # + return - Roles assigned successfully 
    remote isolated function assignRoleToGroup(string id, AssignRoleToGroupRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/groups/${getEncodedUri(id)}/assign`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Revoke a role from a group
    #
    # + id - The name of the group
    # + headers - Headers to be sent with the request 
    # + payload - Roles to revoke from the group and the group type 
    # + return - Roles revoked successfully 
    remote isolated function revokeRoleFromGroup(string id, RevokeRoleFromGroupRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/authz/groups/${getEncodedUri(id)}/revoke`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get roles assigned to a specific group
    #
    # + id - The unique name of the group
    # + groupType - The type of the group
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A list of roles assigned to the specified group 
    remote isolated function getGroupRoles(string id, "oidc" groupType, map<string|string[]> headers = {}, *GetGroupRolesQueries queries) returns RolesListResponse|error {
        string resourcePath = string `/authz/groups/${getEncodedUri(id)}/roles/${getEncodedUri(groupType)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # List all groups of a specific type
    #
    # + groupType - The type of group to retrieve
    # + headers - Headers to be sent with the request 
    # + return - A list of group names for the specified type 
    remote isolated function listGroups("oidc" groupType, map<string|string[]> headers = {}) returns string[]|error {
        string resourcePath = string `/authz/groups/${getEncodedUri(groupType)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List objects
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful response containing the list of objects. If the collection name (`class`) is not provided, the response will not include any objects 
    remote isolated function listObjects(map<string|string[]> headers = {}, *ListObjectsQueries queries) returns ObjectsListResponse|error {
        string resourcePath = string `/objects`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create an object
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The object to be created 
    # + return - Object created successfully 
    remote isolated function createObject(WeaviateObject payload, map<string|string[]> headers = {}, *CreateObjectQueries queries) returns WeaviateObject|error {
        string resourcePath = string `/objects`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get an object by ID
    #
    # + id - Unique UUID of the object to be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful response containing the object 
    # 
    # # Deprecated
    @deprecated
    remote isolated function getObject(string id, map<string|string[]> headers = {}, *GetObjectQueries queries) returns WeaviateObject|error {
        string resourcePath = string `/objects/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update an object
    #
    # + id - Unique UUID of the object to be replaced
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The object definition to replace the existing object with 
    # + return - Object replaced successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function replaceObject(string id, WeaviateObject payload, map<string|string[]> headers = {}, *ReplaceObjectQueries queries) returns WeaviateObject|error {
        string resourcePath = string `/objects/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete an object by ID
    #
    # + id - Unique UUID of the object to be deleted
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Object deleted successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function deleteObject(string id, map<string|string[]> headers = {}, *DeleteObjectQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Patch an object by ID
    #
    # + id - Unique UUID of the object to be patched
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - RFC 7396-style JSON merge patch object containing the fields to update 
    # + return - Object patched successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function updateObject(string id, WeaviateObject payload, map<string|string[]> headers = {}, *UpdateObjectQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Check if an object exists by ID
    #
    # + id - Unique UUID of the object to check
    # + headers - Headers to be sent with the request 
    # + return - Object exists 
    # 
    # # Deprecated
    @deprecated
    remote isolated function checkObjectExists(string id, map<string|string[]> headers = {}) returns http:Response|error {
        string resourcePath = string `/objects/${getEncodedUri(id)}`;
        return self.clientEp->head(resourcePath, headers);
    }

    # Get an object
    #
    # + className - Name of the collection (class) the object belongs to
    # + id - Unique UUID of the object to be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful response containing the object 
    remote isolated function getCollectionObject(string className, string id, map<string|string[]> headers = {}, *GetCollectionObjectQueries queries) returns WeaviateObject|error {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Replace an object
    #
    # + className - Name of the collection (class) the object belongs to
    # + id - Unique UUID of the object to be replaced
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The object definition to replace the existing object with 
    # + return - Object replaced successfully 
    remote isolated function replaceCollectionObject(string className, string id, WeaviateObject payload, map<string|string[]> headers = {}, *ReplaceCollectionObjectQueries queries) returns WeaviateObject|error {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete an object
    #
    # + className - Name of the collection (class) the object belongs to
    # + id - Unique UUID of the object to be deleted
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Object deleted successfully 
    remote isolated function deleteCollectionObject(string className, string id, map<string|string[]> headers = {}, *DeleteCollectionObjectQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Patch an object
    #
    # + className - Name of the collection (class) the object belongs to
    # + id - Unique UUID of the object to be patched
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - RFC 7396-style JSON merge patch object containing the fields to update 
    # + return - Object patched successfully 
    remote isolated function updateCollectionObject(string className, string id, WeaviateObject payload, map<string|string[]> headers = {}, *UpdateCollectionObjectQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Check if an object exists
    #
    # + className - Name of the collection (class) the object belongs to
    # + id - Unique UUID of the object to check
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Object exists 
    remote isolated function checkCollectionObjectExists(string className, string id, map<string|string[]> headers = {}, *CheckCollectionObjectExistsQueries queries) returns http:Response|error {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->head(resourcePath, headers);
    }

    # Replace object references by object ID
    #
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The new list of references 
    # + return - References replaced successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function replaceObjectReferences(string id, string propertyName, MultipleRef payload, map<string|string[]> headers = {}, *ReplaceObjectReferencesQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Add an object reference by object ID
    #
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The reference to add 
    # + return - Reference added successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function addObjectReference(string id, string propertyName, SingleRef payload, map<string|string[]> headers = {}, *AddObjectReferenceQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete an object reference by object ID
    #
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The reference to remove 
    # + return - Reference deleted successfully 
    # 
    # # Deprecated
    @deprecated
    remote isolated function deleteObjectReference(string id, string propertyName, SingleRef payload, map<string|string[]> headers = {}, *DeleteObjectReferenceQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Replace object references
    #
    # + className - Name of the collection (class) the source object belongs to
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The new list of references 
    # + return - References replaced successfully 
    remote isolated function replaceCollectionObjectReferences(string className, string id, string propertyName, MultipleRef payload, map<string|string[]> headers = {}, *ReplaceCollectionObjectReferencesQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Add an object reference
    #
    # + className - Name of the collection (class) the source object belongs to
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The reference to add 
    # + return - Reference added successfully 
    remote isolated function addCollectionObjectReference(string className, string id, string propertyName, SingleRef payload, map<string|string[]> headers = {}, *AddCollectionObjectReferenceQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete an object reference
    #
    # + className - Name of the collection (class) the source object belongs to
    # + id - Unique UUID of the source object
    # + propertyName - Unique name of the reference property of the source object
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The reference to remove 
    # + return - Reference deleted successfully 
    remote isolated function deleteCollectionObjectReference(string className, string id, string propertyName, SingleRef payload, map<string|string[]> headers = {}, *DeleteCollectionObjectReferenceQueries queries) returns error? {
        string resourcePath = string `/objects/${getEncodedUri(className)}/${getEncodedUri(id)}/references/${getEncodedUri(propertyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Validate an object
    #
    # + headers - Headers to be sent with the request 
    # + payload - The object definition to validate 
    # + return - Object is valid according to the schema 
    remote isolated function validateObject(WeaviateObject payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/objects/validate`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Create objects in batch
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request body containing the objects to be created 
    # + return - Request processed successfully. Individual object statuses are provided in the response body 
    remote isolated function createObjectsBatch(BatchObjectsBody payload, map<string|string[]> headers = {}, *CreateObjectsBatchQueries queries) returns ObjectsGetResponse[]|error {
        string resourcePath = string `/batch/objects`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete objects in batch
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request body containing the match filter and output configuration 
    # + return - Request processed successfully. See response body for matching objects and deletion results 
    remote isolated function deleteObjectsBatch(BatchDelete payload, map<string|string[]> headers = {}, *DeleteObjectsBatchQueries queries) returns BatchDeleteResponse|error {
        string resourcePath = string `/batch/objects`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Create cross-references in bulk
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - A list of references to be batched. The ideal size depends on the used database connector. Please see the documentation of the used connector for help 
    # + return - Request Successful. Warning: A successful request does not guarantee that every batched reference was successfully created. Inspect the response body to see which references succeeded and which failed 
    remote isolated function createReferencesBatch(BatchReference[] payload, map<string|string[]> headers = {}, *CreateReferencesBatchQueries queries) returns BatchReferenceResponse[]|error {
        string resourcePath = string `/batch/references`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Perform a GraphQL query
    #
    # + headers - Headers to be sent with the request 
    # + payload - The GraphQL query to execute, including the query string and optional variables 
    # + return - Query executed successfully. The response body contains the query result 
    remote isolated function executeGraphql(GraphQLQuery payload, map<string|string[]> headers = {}) returns GraphQLResponse|error {
        string resourcePath = string `/graphql`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Perform batched GraphQL queries
    #
    # + headers - Headers to be sent with the request 
    # + payload - An array containing multiple GraphQL query objects to execute in batch 
    # + return - Batch request processed successfully. The response body contains an array of results corresponding to the input queries 
    remote isolated function executeGraphqlBatch(GraphQLQueries payload, map<string|string[]> headers = {}) returns GraphQLResponses|error {
        string resourcePath = string `/graphql/batch`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get instance metadata
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved meta information 
    remote isolated function getInstanceMeta(map<string|string[]> headers = {}) returns Meta|error {
        string resourcePath = string `/meta`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Tokenize text
    #
    # + headers - Headers to be sent with the request 
    # + payload - Text to tokenize and the tokenization method to apply 
    # + return - Successfully tokenized the text 
    remote isolated function tokenizeText(TokenizeRequest payload, map<string|string[]> headers = {}) returns TokenizeResponse|error {
        string resourcePath = string `/tokenize`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get all collection definitions
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the database schema 
    remote isolated function listCollections(ListCollectionsHeaders headers = {}) returns Schema|error {
        string resourcePath = string `/schema`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a new collection
    #
    # + headers - Headers to be sent with the request 
    # + payload - The definition of the collection (class) to create 
    # + return - Collection created successfully and its definition returned 
    remote isolated function createCollection(Collection payload, map<string|string[]> headers = {}) returns Collection|error {
        string resourcePath = string `/schema`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a single collection
    #
    # + className - The name of the collection (class) to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the collection definition 
    remote isolated function getCollection(string className, GetCollectionHeaders headers = {}) returns Collection|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update collection definition
    #
    # + className - The name of the collection (class) to update
    # + headers - Headers to be sent with the request 
    # + payload - The updated collection definition containing the settings to modify 
    # + return - Collection settings updated successfully 
    remote isolated function updateCollection(string className, Collection payload, map<string|string[]> headers = {}) returns Collection|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete a collection (and all associated data)
    #
    # + className - The name of the collection (class) to delete
    # + headers - Headers to be sent with the request 
    # + return - Collection deleted successfully 
    remote isolated function deleteCollection(string className, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/schema/${getEncodedUri(className)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Add a property to a collection
    #
    # + className - The name of the collection (class) to add the property to
    # + headers - Headers to be sent with the request 
    # + payload - The definition of the property to add 
    # + return - Property added successfully and its definition returned 
    remote isolated function addCollectionProperty(string className, Property payload, map<string|string[]> headers = {}) returns Property|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get index status for all properties of a collection
    #
    # + headers - Headers to be sent with the request 
    # + return - Index status for all properties 
    remote isolated function getCollectionIndexes(string className, map<string|string[]> headers = {}) returns IndexStatusResponse|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/indexes`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Declaratively create or migrate a property's inverted index
    #
    # + className - The name of the collection (class) containing the property
    # + propertyName - The name of the property whose inverted index should be upserted
    # + indexName - The inverted index type to upsert. `rangeable` is accepted as a write-path alias for `rangeFilters`
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Index configuration to create or migrate on the property 
    # + return - Desired configuration already in place AND no reindex task in flight; no task submitted. Body carries `{"status":"NO_OP"}` 
    remote isolated function upsertPropertyIndex(string className, string propertyName, "filterable"|"searchable"|"rangeFilters"|"rangeable" indexName, IndexUpsertRequest payload, map<string|string[]> headers = {}, *UpsertPropertyIndexQueries queries) returns IndexUpdateResponse|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties/${getEncodedUri(propertyName)}/index/${getEncodedUri(indexName)}`;
        map<Encoding> queryParamEncoding = {"tenants": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete a property's inverted index
    #
    # + className - The name of the collection (class) containing the property
    # + propertyName - The name of the property whose inverted index should be deleted
    # + indexName - The name of the inverted index to delete from the property. `rangeable` is accepted as a write-path alias for `rangeFilters`
    # + headers - Headers to be sent with the request 
    # + return - Index deleted successfully 
    remote isolated function deletePropertyIndex(string className, string propertyName, "filterable"|"searchable"|"rangeFilters"|"rangeable" indexName, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties/${getEncodedUri(propertyName)}/index/${getEncodedUri(indexName)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Rebuild a property's inverted index with unchanged configuration
    #
    # + className - The name of the collection (class) containing the property
    # + propertyName - The name of the property whose inverted index should be rebuilt
    # + indexName - The inverted index type to rebuild. `rangeable` is accepted as a write-path alias for `rangeFilters`
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Reindex task submitted 
    remote isolated function rebuildPropertyIndex(string className, string propertyName, "filterable"|"searchable"|"rangeFilters"|"rangeable" indexName, map<string|string[]> headers = {}, *RebuildPropertyIndexQueries queries) returns IndexUpdateResponse|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties/${getEncodedUri(propertyName)}/index/${getEncodedUri(indexName)}/rebuild`;
        map<Encoding> queryParamEncoding = {"tenants": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Cancel the in-flight reindex task on a property's inverted index
    #
    # + className - The name of the collection (class) containing the property
    # + propertyName - The name of the property whose reindex task should be cancelled
    # + indexName - The inverted index type whose in-flight task should be cancelled. `rangeable` is accepted as a write-path alias for `rangeFilters`
    # + headers - Headers to be sent with the request 
    # + return - Cancellation processed. Body carries `{"status":"CANCELLED","taskId":...}` when a STARTED task was cancelled, or `{"status":"NO_OP"}` when there was nothing to cancel 
    remote isolated function cancelPropertyReindex(string className, string propertyName, "filterable"|"searchable"|"rangeFilters"|"rangeable" indexName, map<string|string[]> headers = {}) returns IndexUpdateResponse|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties/${getEncodedUri(propertyName)}/index/${getEncodedUri(indexName)}/cancel`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Tokenize text using a property's configuration
    #
    # + className - The name of the collection (class) containing the property
    # + propertyName - The name of the property whose tokenization configuration should be used
    # + headers - Headers to be sent with the request 
    # + payload - Text to tokenize using the property's tokenization settings 
    # + return - Successfully tokenized the text using the property's configuration 
    remote isolated function tokenizePropertyText(string className, string propertyName, PropertyTokenizeRequest payload, map<string|string[]> headers = {}) returns TokenizeResponse|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/properties/${getEncodedUri(propertyName)}/tokenize`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a collection's vector index.
    #
    # + className - The name of the collection (class) containing the property
    # + vectorIndexName - The name of the vector index
    # + headers - Headers to be sent with the request 
    # + return - Vector index deleted successfully 
    remote isolated function deleteVectorIndex(string className, string vectorIndexName, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/schema/${getEncodedUri(className)}/vectors/${getEncodedUri(vectorIndexName)}/index`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get the shards status of a collection
    #
    # + className - The name of the collection (class) whose shards to query
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Shard statuses retrieved successfully 
    remote isolated function listCollectionShards(string className, map<string|string[]> headers = {}, *ListCollectionShardsQueries queries) returns ShardStatusList|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/shards`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a shard status
    #
    # + className - The name of the collection (class) containing the shard
    # + shardName - The name of the shard to update
    # + headers - Headers to be sent with the request 
    # + payload - The shard status object containing the desired new status 
    # + return - Shard status updated successfully 
    remote isolated function updateShardStatus(string className, string shardName, ShardStatus payload, map<string|string[]> headers = {}) returns ShardStatus|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/shards/${getEncodedUri(shardName)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Get the list of tenants
    #
    # + className - The name of the collection (class) whose tenants to list
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved tenants 
    remote isolated function listTenants(string className, ListTenantsHeaders headers = {}) returns Tenant[]|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update a tenant
    #
    # + className - The name of the collection (class) containing the tenants
    # + headers - Headers to be sent with the request 
    # + payload - An array of tenant objects specifying the tenants to update and their desired new status 
    # + return - Tenant statuses updated successfully 
    remote isolated function updateTenants(string className, Tenant[] payload, map<string|string[]> headers = {}) returns Tenant[]|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Create a new tenant
    #
    # + className - The name of the multi-tenant enabled collection (class)
    # + headers - Headers to be sent with the request 
    # + payload - An array of tenant objects to create 
    # + return - Tenants created successfully 
    remote isolated function createTenants(string className, Tenant[] payload, map<string|string[]> headers = {}) returns Tenant[]|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete tenants
    #
    # + className - The name of the collection (class) from which to delete tenants
    # + headers - Headers to be sent with the request 
    # + payload - An array of tenant names to delete 
    # + return - Tenants deleted successfully 
    remote isolated function deleteTenants(string className, string[] payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Get a specific tenant
    #
    # + className - The name of the collection (class) containing the tenant
    # + tenantName - The name of the tenant to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved tenant details 
    remote isolated function getTenant(string className, string tenantName, GetTenantHeaders headers = {}) returns Tenant|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants/${getEncodedUri(tenantName)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Check if a tenant exists
    #
    # + className - The name of the collection (class) to check within
    # + tenantName - The name of the tenant to check for
    # + headers - Headers to be sent with the request 
    # + return - The tenant exists in the specified collection 
    remote isolated function checkTenantExists(string className, string tenantName, CheckTenantExistsHeaders headers = {}) returns http:Response|error {
        string resourcePath = string `/schema/${getEncodedUri(className)}/tenants/${getEncodedUri(tenantName)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->head(resourcePath, httpHeaders);
    }

    # List aliases
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the list of aliases 
    remote isolated function listAliases(map<string|string[]> headers = {}, *ListAliasesQueries queries) returns AliasResponse|error {
        string resourcePath = string `/aliases`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a new alias
    #
    # + headers - Headers to be sent with the request 
    # + payload - Alias name and the collection it should point to 
    # + return - Successfully created a new alias for the specified collection (class) 
    remote isolated function createAlias(Alias payload, map<string|string[]> headers = {}) returns Alias|error {
        string resourcePath = string `/aliases`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get an alias
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the alias details 
    remote isolated function getAlias(string aliasName, map<string|string[]> headers = {}) returns Alias|error {
        string resourcePath = string `/aliases/${getEncodedUri(aliasName)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update an alias
    #
    # + headers - Headers to be sent with the request 
    # + payload - The collection that the alias should point to 
    # + return - Successfully updated the alias to point to the new collection (class) 
    remote isolated function updateAlias(string aliasName, UpdateAliasRequest payload, map<string|string[]> headers = {}) returns Alias|error {
        string resourcePath = string `/aliases/${getEncodedUri(aliasName)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete an alias
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted the alias 
    remote isolated function deleteAlias(string aliasName, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/aliases/${getEncodedUri(aliasName)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List namespaces
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the list of namespaces (possibly empty) 
    remote isolated function listNamespaces(map<string|string[]> headers = {}) returns NamespaceListResponse|error {
        string resourcePath = string `/namespaces`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get a namespace
    #
    # + namespaceId - The name of the namespace
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the namespace 
    remote isolated function getNamespace(string namespaceId, map<string|string[]> headers = {}) returns Namespace|error {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a namespace
    #
    # + namespaceId - The name of the namespace
    # + headers - Headers to be sent with the request 
    # + payload - Required body. `home_node` is the new placement target 
    # + return - Namespace updated successfully 
    remote isolated function updateNamespace(string namespaceId, NamespaceUpdateRequest payload, map<string|string[]> headers = {}) returns Namespace|error {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Create a new namespace
    #
    # + namespaceId - The name of the namespace. Must start with a lowercase letter, contain only lowercase letters and digits, length 3-36, and not be a reserved name
    # + headers - Headers to be sent with the request 
    # + payload - Optional body. When omitted, `home_node` is picked automatically 
    # + return - Namespace created successfully 
    remote isolated function createNamespace(string namespaceId, NamespaceCreateRequest payload, map<string|string[]> headers = {}) returns Namespace|error {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a namespace
    #
    # + namespaceId - The name of the namespace
    # + headers - Headers to be sent with the request 
    # + return - The namespace has been marked for deletion. Cleanup of its classes, aliases, and users completes asynchronously 
    remote isolated function deleteNamespace(string namespaceId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Suspend a namespace
    #
    # + namespaceId - The name of the namespace
    # + headers - Headers to be sent with the request 
    # + return - The state change is committed and the namespace is suspended 
    remote isolated function suspendNamespace(string namespaceId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}/suspend`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Resume a namespace
    #
    # + namespaceId - The name of the namespace
    # + headers - Headers to be sent with the request 
    # + return - The state change is committed and the namespace is active 
    remote isolated function resumeNamespace(string namespaceId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/namespaces/${getEncodedUri(namespaceId)}/resume`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # List all created backups
    #
    # + backend - Specifies the backend storage system to list backups from (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the list of backups in progress 
    remote isolated function listBackups(string backend, map<string|string[]> headers = {}, *ListBackupsQueries queries) returns BackupListResponse|error {
        string resourcePath = string `/backups/${getEncodedUri(backend)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a backup
    #
    # + backend - Specifies the backend storage system where the backup will be stored (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + headers - Headers to be sent with the request 
    # + payload - Details of the backup request, including the backup ID and collections to include or exclude 
    # + return - Backup creation process initiated successfully. Check the status endpoint for progress 
    remote isolated function createBackup(string backend, BackupCreateRequest payload, map<string|string[]> headers = {}) returns BackupCreateResponse|error {
        string resourcePath = string `/backups/${getEncodedUri(backend)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get backup creation status
    #
    # + backend - Specifies the backend storage system where the backup resides (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + id - The unique identifier of the backup. Must be URL-safe and compatible with filesystem paths (only lowercase, numbers, underscore, minus characters allowed)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the status of the backup creation process 
    remote isolated function getBackupStatus(string backend, string id, map<string|string[]> headers = {}, *GetBackupStatusQueries queries) returns BackupCreateStatusResponse|error {
        string resourcePath = string `/backups/${getEncodedUri(backend)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Cancel a backup
    #
    # + backend - Specifies the backend storage system where the backup resides (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + id - The unique identifier of the backup to cancel. Must be URL-safe and compatible with filesystem paths (only lowercase, numbers, underscore, minus characters allowed)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Backup canceled successfully 
    remote isolated function cancelBackup(string backend, string id, map<string|string[]> headers = {}, *CancelBackupQueries queries) returns error? {
        string resourcePath = string `/backups/${getEncodedUri(backend)}/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get backup restoration status
    #
    # + backend - Specifies the backend storage system where the backup resides (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + id - The unique identifier of the backup being restored. Must be URL-safe and compatible with filesystem paths (only lowercase, numbers, underscore, minus characters allowed)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the status of the backup restoration process 
    remote isolated function getBackupRestoreStatus(string backend, string id, map<string|string[]> headers = {}, *GetBackupRestoreStatusQueries queries) returns BackupRestoreStatusResponse|error {
        string resourcePath = string `/backups/${getEncodedUri(backend)}/${getEncodedUri(id)}/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Restore from a backup
    #
    # + backend - Specifies the backend storage system where the backup resides (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + id - The unique identifier of the backup to restore from. Must be URL-safe and compatible with filesystem paths (only lowercase, numbers, underscore, minus characters allowed)
    # + headers - Headers to be sent with the request 
    # + payload - Details of the restore request, including collections to include or exclude and node mapping if necessary 
    # + return - Backup restoration process initiated successfully. Check the status endpoint for progress 
    remote isolated function restoreBackup(string backend, string id, BackupRestoreRequest payload, map<string|string[]> headers = {}) returns BackupRestoreResponse|error {
        string resourcePath = string `/backups/${getEncodedUri(backend)}/${getEncodedUri(id)}/restore`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Cancel a backup restoration
    #
    # + backend - Specifies the backend storage system where the backup resides (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + id - The unique identifier of the backup restoration to cancel. Must be URL-safe and compatible with filesystem paths (only lowercase, numbers, underscore, minus characters allowed)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Backup restoration cancelled successfully 
    remote isolated function cancelBackupRestore(string backend, string id, map<string|string[]> headers = {}, *CancelBackupRestoreQueries queries) returns error? {
        string resourcePath = string `/backups/${getEncodedUri(backend)}/${getEncodedUri(id)}/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Start a new export
    #
    # + backend - The backend storage system to use for the export (e.g., `filesystem`, `gcs`, `s3`, `azure`)
    # + headers - Headers to be sent with the request 
    # + payload - Export identifier and the collections and file format to export 
    # + return - Successfully started export operation 
    remote isolated function createExport(string backend, ExportCreateRequest payload, map<string|string[]> headers = {}) returns ExportCreateResponse|error {
        string resourcePath = string `/export/${getEncodedUri(backend)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get export status
    #
    # + backend - The backend storage system where the export is stored
    # + id - The unique identifier of the export
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved export status 
    remote isolated function getExportStatus(string backend, string id, map<string|string[]> headers = {}) returns ExportStatusResponse|error {
        string resourcePath = string `/export/${getEncodedUri(backend)}/${getEncodedUri(id)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Cancel an export
    #
    # + backend - The backend storage system where the export is stored
    # + id - The unique identifier of the export to cancel
    # + headers - Headers to be sent with the request 
    # + return - Export cancelled successfully 
    remote isolated function cancelExport(string backend, string id, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/export/${getEncodedUri(backend)}/${getEncodedUri(id)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get cluster statistics
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved Raft cluster statistics 
    remote isolated function getClusterStatistics(map<string|string[]> headers = {}) returns ClusterStatisticsResponse|error {
        string resourcePath = string `/cluster/statistics`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get node status
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the status for all nodes 
    remote isolated function listNodes(map<string|string[]> headers = {}, *ListNodesQueries queries) returns NodesStatusResponse|error {
        string resourcePath = string `/nodes`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get node status by collection
    #
    # + className - The name of the collection (class) for which to retrieve node status
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved the status for nodes relevant to the specified collection 
    remote isolated function listCollectionNodes(string className, map<string|string[]> headers = {}, *ListCollectionNodesQueries queries) returns NodesStatusResponse|error {
        string resourcePath = string `/nodes/${getEncodedUri(className)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists all distributed tasks in the cluster
    #
    # + headers - Headers to be sent with the request 
    # + return - Distributed tasks successfully returned 
    remote isolated function listDistributedTasks(map<string|string[]> headers = {}) returns DistributedTasks|error {
        string resourcePath = string `/tasks`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Start a classification
    #
    # + headers - Headers to be sent with the request 
    # + payload - Configuration parameters for the classification task, including type, target properties, and training data references 
    # + return - Classification task successfully initiated. The response body contains the classification details including its ID 
    remote isolated function startClassification(Classification payload, map<string|string[]> headers = {}) returns Classification|error {
        string resourcePath = string `/classifications/`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get classification status
    #
    # + id - The unique identifier (UUID) of the classification task
    # + headers - Headers to be sent with the request 
    # + return - Successfully retrieved the classification details 
    remote isolated function getClassification(string id, map<string|string[]> headers = {}) returns Classification|error {
        string resourcePath = string `/classifications/${getEncodedUri(id)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Send an MCP JSON-RPC request
    #
    # + headers - Headers to be sent with the request 
    # + payload - JSON-RPC 2.0 request message 
    # + return - JSON-RPC response or SSE stream 
    remote isolated function sendMcpRequest(record {} payload, map<string|string[]> headers = {}) returns record {}|error {
        string resourcePath = string `/mcp`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # End an MCP session
    #
    # + headers - Headers to be sent with the request 
    # + return - Accepted; there is no session state to terminate 
    remote isolated function endMcpSession(map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/mcp`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Aggregate over a collection
    #
    # + collection - The name (or alias) of the collection to aggregate over. A lowercase first letter is normalized to the canonical uppercase form
    # + headers - Headers to be sent with the request 
    # + payload - The aggregate request 
    # + return - Aggregation performed successfully 
    remote isolated function aggregateCollection(string collection, AggregateRequest payload, map<string|string[]> headers = {}) returns AggregateResponse|error {
        string resourcePath = string `/aggregate/${getEncodedUri(collection)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Search a collection with bm25
    #
    # + collection - The name (or alias) of the collection to search. A lowercase first letter is normalized to the canonical uppercase form
    # + headers - Headers to be sent with the request 
    # + payload - The bm25 search request 
    # + return - Search performed successfully 
    remote isolated function searchBm25(string collection, SearchBm25Request payload, map<string|string[]> headers = {}) returns SearchResponse|error {
        string resourcePath = string `/search/${getEncodedUri(collection)}/bm25`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Search a collection with hybrid
    #
    # + collection - The name (or alias) of the collection to search. A lowercase first letter is normalized to the canonical uppercase form
    # + headers - Headers to be sent with the request 
    # + payload - The hybrid search request 
    # + return - Search performed successfully 
    remote isolated function searchHybrid(string collection, SearchHybridRequest payload, map<string|string[]> headers = {}) returns SearchResponse|error {
        string resourcePath = string `/search/${getEncodedUri(collection)}/hybrid`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Search a collection with near-object
    #
    # + collection - The name (or alias) of the collection to search. A lowercase first letter is normalized to the canonical uppercase form
    # + headers - Headers to be sent with the request 
    # + payload - The near-object search request 
    # + return - Search performed successfully 
    remote isolated function searchNearObject(string collection, SearchNearObjectRequest payload, map<string|string[]> headers = {}) returns SearchResponse|error {
        string resourcePath = string `/search/${getEncodedUri(collection)}/near-object`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Search a collection with near-text
    #
    # + collection - The name (or alias) of the collection to search. A lowercase first letter is normalized to the canonical uppercase form
    # + headers - Headers to be sent with the request 
    # + payload - The near-text search request 
    # + return - Search performed successfully 
    remote isolated function searchNearText(string collection, SearchNearTextRequest payload, map<string|string[]> headers = {}) returns SearchResponse|error {
        string resourcePath = string `/search/${getEncodedUri(collection)}/near-text`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }
}
